version: 2.1

executors:
  macos-executor:
    macos:
      xcode: "12.5.0"  # Ensure the correct Xcode version

jobs:
  install_dependencies:
    executor: macos-executor
    steps:
      - checkout
      - run:
          name: Install Homebrew
          command: |
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - run:
          name: Install Node.js
          command: |
            brew install node
      - run:
          name: Install npm dependencies
          command: npm install

  build:
    executor: macos-executor
    steps:
      - checkout
      - run:
          name: Build Electron App for macOS
          command: npm run build -- --mac  # Trigger the Electron build

  deploy:
    executor: macos-executor
    steps:
      - checkout
      - run:
          name: Deploy build artifact (optional)
          command: |
            echo "Deploy step goes here."

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install_dependencies
      - build:
          requires:
            - install_dependencies
      - deploy:
          requires:
            - build
